---
version: '3'
silent: true
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  hello:
    cmds:
      - echo "Task works ok!!!"

  setup:
    cmds:
      - test -f .env && echo "==========> .env file already exists" || cp .env.example .env

  build:
    cmds:
      - go build -o tmdbcli .

  test:
    cmds:
      - go test ./... -v

  air:
    cmds:
      - air
