---
version: '3.8'
services:
  db:
    image: mysql:8.0.32
    restart: "no"
    env_file:
      - compose.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USERNAME_NONROOT}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD_NONROOT}
      # Password for root access empty
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      # <Port exposed on host machine> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      # <Volume name>:<Container Datas>
      - gobatchservicedbvol01:/var/lib/mysql
    # https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,ALLOW_INVALID_DATES
# Names our volume
volumes:
  gobatchservicedbvol01:
