{
 "title": "fronzec/memkv",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "memkv", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"memkv\"}[15s]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"memkv\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"memkv\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GET /key RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_count{\n  job=\"memkv\", endpoint=\"/keys\", method=\"GET\"\n}[15s]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "GET /key Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(http_request_errors{\n  job=\"memkv\", endpoint=\"/keys\", method=\"GET\"\n}[15s]))\n/\nsum(irate(http_requests_count{\n  job=\"memkv\", endpoint=\"/keys\", method=\"GET\"\n}[15s])))\n# OR on() vector(0)",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "GET /key Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(http_requests{\n  job=\"memkv\", endpoint=\"/keys\", method=\"GET\"\n}) by (quantile)",
     "legendFormat": "p{{quantile}}"
    }
   ]
  },
  {
   "title": "POST /key RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_count{\n  job=\"memkv\", endpoint=\"/keys\", method=\"POST\"\n}[15s]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "POST /key Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(http_request_errors{\n  job=\"memkv\", endpoint=\"/keys\", method=\"POST\"\n}[15s]))\n/\nsum(irate(http_requests_count{\n  job=\"memkv\", endpoint=\"/keys\", method=\"POST\"\n}[15s])))\n# OR on() vector(0)",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "POST /key Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(http_requests{\n  job=\"memkv\", endpoint=\"/keys\", method=\"POST\"\n}) by (quantile)",
     "legendFormat": "p{{quantile}}"
    }
   ]
  }
 ]
}