# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./todo-service/...

    - name: Test
      run: go test -v ./todo-service/...

    
    - name: Build 2
      run: go build -v ./go-chi-restful-api/...

    - name: Test 2
      run: go test -v ./go-chi-restful-api/...
