# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build go-chi-restful-api
      run: cd ./go-chi-restful-api && go build -v ./...

    - name: Test go-chi-restful-api
      run: cd ./go-chi-restful-api && go test -v ./...

    - name: Build memvk
      run: cd memkv && go build -v ./...

    - name: Test memvk
      run: cd memkv && go test -v ./...
