# This workflow builds and tests every Go module in the monorepo.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - go-chi-restful-api
          - markdown-note-taking-app
          - memkv
          - secmoney
          - tmdbcli
          - weather-service
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ matrix.module }}/go.mod"
          cache-dependency-path: "${{ matrix.module }}/go.sum"

      - name: Build ${{ matrix.module }}
        run: cd ./${{ matrix.module }} && go build -v ./...

      - name: Vet ${{ matrix.module }}
        run: cd ./${{ matrix.module }} && go vet ./...

      - name: Test ${{ matrix.module }}
        run: cd ./${{ matrix.module }} && go test -v ./...
